version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/test-assessment-db
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
  frontend:
    build: reacj-js-frontend-test/
    ports:
      - '3001:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://node-app:3000/v1

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
